.TH "CG" "1" "April 17, 2002" "NiH" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBcg\fR
\- semi-automatic newsgroup binary downloader
.SH "SYNOPSIS"
.HP 3n
\fBcg\fR
[\fB\-chmV\fR]
[\fB\-n\fR\ \fIrcfile\fR]
[\fB\-p\fR\ \fIpasswd\fR]
[\fB\-s\fR\ \fIserver\fR]
[\fB\-u\fR\ \fIuser\fR]
\fIgroup\ ...\fR
.SH "DESCRIPTION"
\fBcg\fR
is a semi-automatic newsgroup binary downloader.
It assembles parts based on subject headers and then offers them in an
editor for the user to choose which files he really wants.
.PP
It supports decoding data in the following formats:
.RS 6n
.PD 0
.TP 10n
MIME
The following message formats are supported: multipart/mixed,
message/partial; the following encodings are supported:
base64, quoted printable, x-uuencode.
.TP 10n
uuencode
Both single- and multi-posting binaries.
.TP 10n
yEnc
Both single- and multi-posting binaries.
.RE
.PD
.PP
The following flags are supported:
.RS 6n
.PD 0
.TP 22n
\fB\-c\fR, \fB\--mark-complete\fR
.br
Mark only parts of complete files as read.
.TP 22n
\fB\-h\fR, \fB\--help\fR
Show a short usage.
.TP 22n
\fB\-n\fR, \fB\--newsrc\fR \fIFILE\fR
Use
\fIFILE\fR
as newsrc file.
.TP 22n
\fB\-p\fR, \fB\--pass\fR \fIPASS\fR
Use
\fIPASS\fR
as password for authentication.
.TP 22n
\fB\-s\fR, \fB\--server\fR \fISERVER\fR
.br
Use
\fISERVER\fR
as NNTP server.
Both IPv4 and IPv6 are supported.
.TP 22n
\fB\-u\fR, \fB\--user\fR \fIUSER\fR
Use
\fIUSER\fR
as user for authentication.
.TP 22n
\fB\-V\fR, \fB\--version\fR
Show release information.
.RE
.PD
.PP
\fBcg\fR
reads the XOVER record from the news server for each group given on
the command line and tries to assemble all unread binaries in this
group.
Then
\fBcg\fR
spawns an editor (taken from the
\fRVISUAL\fR
or
\fREDITOR\fR
environment variables, or defaulting to
vi(1))
where the user can delete all lines of unwanted binaries.
After leaving the editor, the binaries corresponding to undelete lines
are decoded and saved in the current directory.
.PP
Comments in 0-parts or around the encoded data are saved in the file
\(lqfilename.desc\(rq;
broken files (problems during decoding, missing parts due to
expiration) are saved as
\(lqfilename.broken\(rq.
Files are not overwritten, rather
\(lq.1\(rq,
\(lq.2\(rq,
\&... is appended to the filename to make it unique.
.SH "ENVIRONMENT"
The
\fRVISUAL\fR
and
\fREDITOR\fR
environment variables are honored in this order.
.PP
Set the
\fRNNTPSERVER\fR
environment variable to choose your newsserver (which must support
xover records), or use the
\fB\-s\fR
flag.
Both IPv4 and IPv6 are supported.
.SH "BUGS"
Mail suggestions and bug reports to
<\fInih@giga.or.at\fR>.
